matrix:
  include:
    - os: windows
      language: sh
      python: 3.6
      env: PYVER="3.6.8" PYDIR="Python36" INCLUDE="$PWD/cairocomplied/include/" LIB="$PWD/cairocomplied/lib/x64/" CAIRO_VERSION=1.15.10
    - os: windows
      language: sh
      python: 3.7
      env: PYVER="3.7.7" PYDIR="Python37" INCLUDE="$PWD/cairocomplied/include/" LIB="$PWD/cairocomplied/lib/x64/" CAIRO_VERSION=1.15.10
    - os: windows
      language: sh
      python: 3.8
      env: PYVER="3.8.3" PYDIR="Python38" INCLUDE="$PWD/cairocomplied/include/" LIB="$PWD/cairocomplied/lib/x64/" PYNAME="3.8" CAIRO_VERSION=1.15.10

install:
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then source .travis/downloadCairo.sh; fi
  - choco install python --version=$PYVER
  - export PATH="/c/$PYDIR:/c/$PYDIR/Scripts:$PATH"
  - cmd.exe //c "RefreshEnv.cmd"
  - python -m pip install --upgrade pip
  - python -m pip install --upgrade wheel
  - python -m pip install --upgrade setuptools
  - python -m pip install pytest
  - python -m pip install --upgrade mypy || true
  - cmd.exe //c "RefreshEnv.cmd"
script:
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then cp cairocomplied/lib/x64/cairo.dll cairo/cairo.dll; fi
  - python setup.py bdist_wheel
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then source .travis/runPycairox86.sh; fi
  #- if [ "$TRAVIS_OS_NAME" == "windows" ]; then source .travis/runPycairox64.sh; fi
  - dir
  - cd dist
  - dir
  - cd ../
  #- python -m pytest
  #- pip install --upgrade pycairo-1.19.2-cp38-cp38-win_amd64.whl || pip install --upgrade pycairo-1.19.2-cp37-cp37m-win_amd64.whl

cache:
  directories:
    - $HOME/.cache/pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
branches:
  only:
  - master
deploy:
  provider: releases
  file_glob: true
  api_key: $GITHUBOAUTHTOKEN
  file: dist/*
  skip_cleanup: true
  draft: true