matrix:
  include:
    - os: windows
      language: shell
      before_install:
        - choco install python --version 3.8.0
        - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"
install:
  - python -m pip install --upgrade wheel
  - python -m pip install --upgrade setuptools
  - python -m pip install --upgrade mypy || true

script:
  - python setup.py install
  - python setup.py bdist_wheel
  - dir
  - git config --global user.name "Travis CI"
  - git checkout -b "travis-build"
  - git add .
  - git commit -m "Updates"
  - git push -u origin travis-build
