name: Build

on: [push]

jobs:
  build_cairo:
    name: Build cairo for Windows
    runs-on: windows-latest
    env:
      CAIRO_VERSION: "1.17.2"
      TOKENACCESS: ${{ secrets.GITHUB_TOKEN }} 
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }} for x64
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          path-type: inherit
          install: git mingw-w64-x86_64-toolchain make
      - name: Build x64 Build
        shell: msys2 {0}
        run: |
           unset TMP
           unset TEMP
           curl -L https://github.com/preshing/cairo-windows/raw/master/build-cairo-windows.sh -o build-cairo-windows.sh
           ./build-cairo-windows.sh
           #C:\msys64\usr\bin\bash -lc './build-cairo-windows.sh'
      - uses: actions/upload-artifact@v2
        with:
         name: wheels-${{ matrix.python-version }}
         path: trymeson/cairo/build
