name: Build

on: [push]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'
      - uses: msys2/setup-msys2@v2
        name: Setup Msys
        with:
          msystem: MSYS
          install: mingw-w64-x86_64-cairo
          update: true
      - shell: msys2 {0}
        run: |
          which cairo.dll
      - name: Where is it?
        run: |
          cmd.exe /C "where cairo.dll"
