name: Build

on: [push]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: windows-latest
    env:
     CAIRO_VERSION:1.17.2
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: [3.6,3.7,3.8,3.9]
      - name: Test path
        run: |
          curl https://github.com/preshing/cairo-windows/releases/download/$CAIRO_VERSION/cairo-windows-$CAIRO_VERSION.zip -o cairocomplied.zip
          7z x cairocomplied.zip
          Move-Item "cairo-windows-*\" "cairocomplied\"
          $env:INCLUDE="$PWD/cairocomplied/include/"
          $env:LIB="$PWD/cairocomplied/lib/x64/"
          Copy-Item cairocomplied/lib/x64/cairo.dll cairo/cairo.dll
          #$env:LIB="D:\a\_temp\msys\msys64\mingw64\lib\"
          python -m pip install --upgrade pip
          python -m pip install --upgrade wheel
          python -m pip install --upgrade setuptools
          python -m pip install --upgrade pytest
          python setup.py install
          python setup.py bdist_wheel
          pytest
      - uses: actions/upload-artifact@v2
        with:
         name: wheels
         path: dist/*
