name: Build Wheels
on: 
  push:
  pull_request:
jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, macos-latest]
    env:
      CIBW_BUILD: "cp37-* cp36-* cp38-* cp39-*"
      CIBW_SKIP: "pp* cp35"
      CIBW_BEFORE_BUILD_LINUX: "yum install -y pkgconfig && yum install -y cairo-devel"
      CIBW_BEFORE_BUILD_MACOS: "brew install cairo"
      CIBW_TEST_REQUIRES: pytest
      CIBW_TEST_COMMAND: "python {project}/setup.py test"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: "3.7"
      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel==1.6.4

      - name: Build wheels (Non-Windows)
        run: |
          python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
          name: wheels-${{ runner.os }}