name: Build

on: [push]

jobs:
  build_cairo:
    name: Build cairo for Windows
    runs-on: windows-latest
    env:
      CAIRO_VERSION: "1.17.2"
      TOKENACCESS: ${{ secrets.GITHUB_TOKEN }} 
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }} for x64
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'
      - name: Build x64 Build
        run: |
           curl -L https://github.com/preshing/cairo-windows/raw/master/build-cairo-windows.sh -o build-cairo-windows.sh
           (New-Object System.Net.WebClient).DownloadFile('https://github.com/msys2/msys2-installer/releases/download/2020-06-29/msys2-base-x86_64-20200629.sfx.exe', 'msys2.exe')
           .\msys2.exe -y -oC:\  # Extract to C:\msys64
           Remove-Item msys2.exe  # Delete the archive again
           C:\msys64\usr\bin\bash -lc ' '
           # Update MSYS2
           C:\msys64\usr\bin\bash -lc 'pacman -Syuu'  # Core update (in case any core packages are outdated)
           C:\msys64\usr\bin\bash -lc 'pacman -Syuu'  # Normal update
           $env:CHERE_INVOKING = 'yes'
           $env:MSYSTEM = 'MINGW64'
           C:\msys64\usr\bin\bash -lc 'pacman -S tar make'
           set PATH=C:\msys64;%PATH%
           msys2_shell.cmd -use-full-path
           unset TMP
           unset TEMP
           ./build-cairo-windows.sh
      - uses: actions/upload-artifact@v2
        with:
         name: wheels-${{ matrix.python-version }}
         path: trymeson/cairo/build
