name: Build

on: [push]

jobs:
  build_wheels:
    name: Build wheels for Windows on ${{ matrix.python-version }}
    runs-on: windows-latest
    env:
      CAIRO_VERSION: "1.17.2"
      TOKENACCESS: ${{ secrets.GITHUB_TOKEN }} 
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }} for x64
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'
      - name: Build x64 Build
        run: |
           tree
           choco install ninja
           pip install meson
           mkdir "trymeson"
           cd "trymeson"
           git clone https://gitlab.freedesktop.org/cairo/cairo.git
           meson cairo && cd cairo
           meson compile
           tree
           meson test
           meson build 
           tree
      - uses: actions/upload-artifact@v2
        with:
         name: wheels-${{ matrix.python-version }}
         path: trymeson/cairo/build/
