name: Build

on: [push]

jobs:
  build_cairo:
    name: Build cairo for Windows
    runs-on: windows-latest
    env:
      CAIRO_VERSION: "1.17.2"
      TOKENACCESS: ${{ secrets.GITHUB_TOKEN }} 
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }} for x64
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          path-type: inherit
          install: git mingw-w64-x86_64-toolchain make
      - name: Download Dependency
        run: |
           curl -L https://eternallybored.org/misc/wget/releases/wget-1.20.3-win64.zip -o wget.zip
           7z x wget.zip -o wget
           cd wget*
           move "wget*" "..\"
           $env:PATH = "$($PWD);$env:PATH"
           $USE_FREETYPE=1
           $CAIRO_VERSION="cairo-1.17.2"
           $PIXMAN_VERSION="pixman-0.40.0"
           $LIBPNG_VERSION="libpng-1.6.37"
           $ZLIB_VERSION="zlib-1.2.11"
           $FREETYPE_VERSION="freetype-2.10.2"
           wget -nc "https://www.cairographics.org/snapshots/$($CAIRO_VERSION).tar.xz"
           wget -nc "https://www.cairographics.org/releases/$($PIXMAN_VERSION.tar).gz"
           wget -nc "https://download.sourceforge.net/libpng/$($LIBPNG_VERSION.tar).gz"
           wget -nc "http://www.zlib.net/$($ZLIB_VERSION).tar.gz"
           wget -nc "http://download.savannah.gnu.org/releases/freetype/$($FREETYPE_VERSION).tar.gz"
           tar -xJf "$($CAIRO_VERSION).tar.xz"
           move "$($CAIRO_VERSION)" "cairo"
           tar -xzf "$($PIXMAN_VERSION).tar.gz"
           move "$($PIXMAN_VERSION)" "pixman"
           tar -xzf "$($LIBPNG_VERSION).tar.gz"
           move "$($LIBPNG_VERSION)" "libpng"
           tar -xzf "$($FREETYPE_VERSION).tar.gz"
           move "$($FREETYPE_VERSION)" "freetype"
           tar -xzf "$($ZLIB_VERSION).tar.gz"
           move "$($ZLIB_VERSION)" "zlib"
      - name: Build x64 Build
        shell: msys2 {0}
        run: |
           unset TMP
           unset TEMP
           curl -L https://github.com/preshing/cairo-windows/raw/master/build-cairo-windows.sh -o build-cairo-windows.sh
           ./build-cairo-windows.sh
           #C:\msys64\usr\bin\bash -lc './build-cairo-windows.sh'
      - uses: actions/upload-artifact@v2
        with:
         name: wheels-${{ matrix.python-version }}
         path: trymeson/cairo/build
