name: Build

on: [push]

jobs:
  build_wheels:
    name: Build wheels for Windows on ${{ matrix.python-version }}
    runs-on: windows-latest
    env:
      CAIRO_VERSION: "1.17.2"
      TOKENACCESS: ${{ secrets.GITHUB_TOKEN }} 
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Download and extract Cairo Binary
        run: |
          mkdir "cairocomplied"
          cd "cairocomplied" && mkdir "include" && cd ../
          curl -L https://github.com/preshing/cairo-windows/releases/download/$($env:CAIRO_VERSION)/cairo-windows-$($env:CAIRO_VERSION).zip -o cairocomplied.zip
          7z x cairocomplied.zip
          Move-Item 'cairo-windows-*\lib' "cairocomplied"
          #Move-Item 'cairocomplied\include\cairo\*' "cairocomplied\include"
          tree
      - name: Set up Python ${{ matrix.python-version }} for x64
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'
      - uses: msys2/setup-msys2@v2
        name: Setup Msys
        with:
          install: git mingw-w64-x86_64-cairo mingw-w64-x86_64-python-cairo mingw-w64-x86_64-python mingw-w64-x86_64-python-pytest
          update: true
      - shell: msys2 {0}
        run: |
          mv "/mingw64/include/cairo/" "cairocomplied/include/"
          mv "/mingw64/lib/pkgconfig/*" "cairocomplied/include/cairo"
          cp "$PWD/cairocomplied/lib/x64/cairo.dll" "cairo/cairo.dll"
          python setup.py bdist_wheel
          
          
      - name: Build x64 Build
        run: |
          tree
          $env:INCLUDE="$PWD\cairocomplied\include\cairo\"
          $env:LIB="$PWD\cairocomplied\lib\x64\"
          Copy-Item "$PWD\cairocomplied\lib\x64\cairo.dll" "cairo\cairo.dll"
          python -m pip install --upgrade pip
          python -m pip install --upgrade wheel
          python -m pip install --upgrade setuptools
          python -m pip install --upgrade pytest flake8 "sphinx<3" sphinx_rtd_theme coverage codecov hypothesis attrs
          python -m pip install --upgrade mypy || true
          python -m pip install --upgrade pygame
          python -m coverage run --branch setup.py test
          python -m codecov --required
          python -m flake8 .
          python setup.py sdist
          python setup.py bdist
          python setup.py install --root=_root
          python setup.py install --root="$(pwd)"/_root_abs
          python setup.py bdist_wheel
          python setup.py install --root=_root_setup
          python -m pip install .
          python -m sphinx -W -a -E -b html -n docs docs/_build
      - name: Set up Python ${{ matrix.python-version }} for x64
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x86'
      - name: Build x64 Build
        run: |
          $env:INCLUDE="$PWD\cairocomplied\include\cairo\"
          $env:LIB="$PWD\cairocomplied\lib\x86\"
          Copy-Item "cairocomplied\lib\x86\cairo.dll" "cairo\cairo.dll"
          python -m pip install --upgrade pip
          python -m pip install --upgrade wheel
          python -m pip install --upgrade setuptools
          python -m pip install --upgrade pytest flake8 "sphinx<3" sphinx_rtd_theme coverage codecov hypothesis attrs
          python -m pip install --upgrade mypy || true
          python -m pip install --upgrade pygame
          python -m coverage run --branch setup.py test
          python -m codecov --required
          python -m flake8 .
          python setup.py sdist
          python setup.py bdist
          python setup.py install --root=_root
          python setup.py install --root="$(pwd)"/_root_abs
          python setup.py bdist_wheel
          python setup.py install --root=_root_setup
          python -m pip install .
          python -m sphinx -W -a -E -b html -n docs docs/_build
      - uses: actions/upload-artifact@v2
        with:
         name: wheels-${{ matrix.python-version }}
         path: dist/pycairo*.whl
